sudo: true
language: python
cache: pip

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy-5.3.1

addons:
  apt:
    packages:
    - minidlna

before_install:
- echo $TRAVIS_BUILD_DIR
- sudo echo "port=8200
  log_dir=/tmp/
  log_level=debug
  friendly_name=test_server
  inotify=yes
  db_dir=/tmp/
  media_dir=${$TRAVIS_BUILD_DIR}/tests/data"

- /usr/sbin/minidlnad -f $confpath -P /tmp/minidlna.pid
- /usr/sbin/minidlnad -R -r
- pip install -U setuptools wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

notifications:
  email:
  - M3RLINK@gmx.de

