sudo: true
language: python
cache: pip

python:
- '2.7'
#- '3.3'
#- '3.4'
#- '3.5'
#- '3.6'
#- pypy
#- pypy-5.3.1

addons:
  apt:
    packages:
    - minidlna

before_install:
- sudo service minidlna stop
- echo $TRAVIS_BUILD_DIR
- sudo cp -Rv "${TRAVIS_BUILD_DIR}/tests/data" /var/lib/minidlna
- ls /var/lib/minidlna
- cat /etc/minidlna.conf
#- sudo echo "port=8200\nlog_dir=/tmp/\nlog_level=debug\nfriendly_name=test_server\ninotify=yes\ndb_dir=/tmp/\nmedia_dir=${TRAVIS_BUILD_DIR}/tests/data" > /etc/minidlna.conf
- sudo service minidlna start
- sudo minidlnad -R
- sudo service minidlna restart
- sleep 3
- sudo service minidlna status
- ls /tmp
#- journalctl -R
#- cat /tmp/minidlna.log
- sleep 3
- pip install -U setuptools wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

notifications:
  email:
  - M3RLINK@gmx.de

