sudo: true
language: python
cache: pip

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy-5.3.1

addons:
  apt:
    packages:
    - minidlna

before_install:
- echo $TRAVIS_BUILD_DIR
- sudo echo "port=8200\nlog_dir=/tmp/\nlog_level=debug\nfriendly_name=test_server\ninotify=yes\ndb_dir=/tmp/\nmedia_dir=${TRAVIS_BUILD_DIR}/tests/data"
- sudo /etc/init.d/minidlna start
- sudo /etc/init.d/minidlna force-reload
- sleep 3
- cat /tmp/minidlna.log
- sleep 3
- pip install -U setuptools wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

notifications:
  email:
  - M3RLINK@gmx.de

